# Docker
- task: CmdLine@2
  inputs:
    script: |
      git checkout master
      git add --all
      git push https://e58163e0386ba3bac83dc93253da73270a7098a3@github.com/fabro020588/apptest.git
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/test/Dockerfile'
        tags: |
          $(tag)